name: popup_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

  http: ^1.2.1
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4

  flutter_dotenv: ^5.1.0

  connectivity_plus: ^6.1.3

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  flutter_map: ^8.1.1
  latlong2: ^0.9.0

  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
    - assets/no_image.png
    - .env
    - assets/icons/

flutter_native_splash:
  color: "#ffffff" # 배경색 (변경 가능)
  image: assets/splash.png # 스플래시 이미지 경로
  android: true
  ios: true