// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXePx5K4j6e3TwXXmBdB1GfJhs2fO1LyU',
    appId: '1:801108681134:android:306c607c24f2b84df2283f',
    messagingSenderId: '801108681134',
    projectId: 'popup-finder-3ef60',
    storageBucket: 'popup-finder-3ef60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfF9BhqLwYUdq5z4RnGTG_AmrMjQJMrCg',
    appId: '1:801108681134:ios:2581e3f0bb518cf2f2283f',
    messagingSenderId: '801108681134',
    projectId: 'popup-finder-3ef60',
    storageBucket: 'popup-finder-3ef60.firebasestorage.app',
    iosBundleId: 'com.example.popupApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfF9BhqLwYUdq5z4RnGTG_AmrMjQJMrCg',
    appId: '1:801108681134:ios:bc4da434d3c884eef2283f',
    messagingSenderId: '801108681134',
    projectId: 'popup-finder-3ef60',
    storageBucket: 'popup-finder-3ef60.firebasestorage.app',
    iosBundleId: 'com.example.popupApp',
  );
}
